-- Synthetic exact-slug public API, no table enumeration or owner identifiers.
BEGIN; SET LOCAL ROLE anon; SELECT set_config('request.jwt.claims', '{"role":"anon","sub":""}',true);
SELECT security_test.check('anon cannot enumerate foreign shared_lists', 'error:42501', 'SELECT count(*)::text FROM public.shared_lists');
SELECT security_test.check('anon cannot read foreign owner columns shared_lists', 'error:42501', 'SELECT count(list_id)::text FROM public.shared_lists WHERE slug=''aaaaaaaaa1''');
SELECT security_test.check('anon cannot enumerate foreign category_shared_lists', 'error:42501', 'SELECT count(*)::text FROM public.category_shared_lists');
SELECT security_test.check('anon cannot read foreign owner columns category_shared_lists', 'error:42501', 'SELECT count(list_id)::text FROM public.category_shared_lists WHERE slug=''aaaaaaaaaaa1''');
SELECT security_test.check('anon reads exact active read_movie_share', '1', 'SELECT count(*)::text FROM public.read_movie_share(''aaaaaaaaa1'')');
SELECT security_test.check('anon rejects read_movie_share ''aaaaaaaaa2''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''aaaaaaaaa2'')');
SELECT security_test.check('anon rejects read_movie_share ''zzzzzzzzzz''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''zzzzzzzzzz'')');
SELECT security_test.check('anon rejects read_movie_share NULL', '0', 'SELECT count(*)::text FROM public.read_movie_share(NULL)');
SELECT security_test.check('anon rejects read_movie_share ''''', '0', 'SELECT count(*)::text FROM public.read_movie_share('''')');
SELECT security_test.check('anon rejects read_movie_share ''%''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''%'')');
SELECT security_test.check('anon rejects read_movie_share ''../aaaaaaaaa1''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''../aaaaaaaaa1'')');
SELECT security_test.check('anon rejects read_movie_share ''AAAAAAAAA1''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''AAAAAAAAA1'')');
SELECT security_test.check('anon RPC omits owner read_movie_share', 'true', 'SELECT bool_and(NOT (to_jsonb(r) ? ''list_id''))::text FROM public.read_movie_share(''aaaaaaaaa1'') r');
SELECT security_test.check('anon reads exact active read_dog_share', '1', 'SELECT count(*)::text FROM public.read_dog_share(''aaaaaaaaaaa1'')');
SELECT security_test.check('anon rejects read_dog_share ''aaaaaaaaaaa2''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''aaaaaaaaaaa2'')');
SELECT security_test.check('anon rejects read_dog_share ''zzzzzzzzzzzz''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''zzzzzzzzzzzz'')');
SELECT security_test.check('anon rejects read_dog_share NULL', '0', 'SELECT count(*)::text FROM public.read_dog_share(NULL)');
SELECT security_test.check('anon rejects read_dog_share ''''', '0', 'SELECT count(*)::text FROM public.read_dog_share('''')');
SELECT security_test.check('anon rejects read_dog_share ''%''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''%'')');
SELECT security_test.check('anon rejects read_dog_share ''../aaaaaaaaaaa1''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''../aaaaaaaaaaa1'')');
SELECT security_test.check('anon rejects read_dog_share ''AAAAAAAAAAA1''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''AAAAAAAAAAA1'')');
SELECT security_test.check('anon RPC omits owner read_dog_share', 'true', 'SELECT bool_and(NOT (to_jsonb(r) ? ''list_id''))::text FROM public.read_dog_share(''aaaaaaaaaaa1'') r');
SELECT security_test.check('anon Movies RPC strips legacy extra keys', 'true', 'SELECT (payload=''{"movies":[]}''::jsonb)::text FROM public.read_movie_share(''legacy0001'')');
ROLLBACK;
BEGIN; SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claims', '{"role":"authenticated","sub":"bbbbbbbb-2222-4222-8222-222222222222"}',true);
SELECT security_test.check('authenticated cannot enumerate foreign shared_lists', '0', 'SELECT count(*)::text FROM public.shared_lists WHERE list_id=''user:aaaaaaaa-1111-4111-8111-111111111111''');
SELECT security_test.check('authenticated cannot read foreign owner columns shared_lists', '0', 'SELECT count(list_id)::text FROM public.shared_lists WHERE slug=''aaaaaaaaa1''');
SELECT security_test.check('authenticated cannot enumerate foreign category_shared_lists', '0', 'SELECT count(*)::text FROM public.category_shared_lists WHERE list_id=''user:aaaaaaaa-1111-4111-8111-111111111111''');
SELECT security_test.check('authenticated cannot read foreign owner columns category_shared_lists', '0', 'SELECT count(list_id)::text FROM public.category_shared_lists WHERE slug=''aaaaaaaaaaa1''');
SELECT security_test.check('authenticated reads exact active read_movie_share', '1', 'SELECT count(*)::text FROM public.read_movie_share(''aaaaaaaaa1'')');
SELECT security_test.check('authenticated rejects read_movie_share ''aaaaaaaaa2''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''aaaaaaaaa2'')');
SELECT security_test.check('authenticated rejects read_movie_share ''zzzzzzzzzz''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''zzzzzzzzzz'')');
SELECT security_test.check('authenticated rejects read_movie_share NULL', '0', 'SELECT count(*)::text FROM public.read_movie_share(NULL)');
SELECT security_test.check('authenticated rejects read_movie_share ''''', '0', 'SELECT count(*)::text FROM public.read_movie_share('''')');
SELECT security_test.check('authenticated rejects read_movie_share ''%''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''%'')');
SELECT security_test.check('authenticated rejects read_movie_share ''../aaaaaaaaa1''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''../aaaaaaaaa1'')');
SELECT security_test.check('authenticated rejects read_movie_share ''AAAAAAAAA1''', '0', 'SELECT count(*)::text FROM public.read_movie_share(''AAAAAAAAA1'')');
SELECT security_test.check('authenticated RPC omits owner read_movie_share', 'true', 'SELECT bool_and(NOT (to_jsonb(r) ? ''list_id''))::text FROM public.read_movie_share(''aaaaaaaaa1'') r');
SELECT security_test.check('authenticated reads exact active read_dog_share', '1', 'SELECT count(*)::text FROM public.read_dog_share(''aaaaaaaaaaa1'')');
SELECT security_test.check('authenticated rejects read_dog_share ''aaaaaaaaaaa2''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''aaaaaaaaaaa2'')');
SELECT security_test.check('authenticated rejects read_dog_share ''zzzzzzzzzzzz''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''zzzzzzzzzzzz'')');
SELECT security_test.check('authenticated rejects read_dog_share NULL', '0', 'SELECT count(*)::text FROM public.read_dog_share(NULL)');
SELECT security_test.check('authenticated rejects read_dog_share ''''', '0', 'SELECT count(*)::text FROM public.read_dog_share('''')');
SELECT security_test.check('authenticated rejects read_dog_share ''%''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''%'')');
SELECT security_test.check('authenticated rejects read_dog_share ''../aaaaaaaaaaa1''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''../aaaaaaaaaaa1'')');
SELECT security_test.check('authenticated rejects read_dog_share ''AAAAAAAAAAA1''', '0', 'SELECT count(*)::text FROM public.read_dog_share(''AAAAAAAAAAA1'')');
SELECT security_test.check('authenticated RPC omits owner read_dog_share', 'true', 'SELECT bool_and(NOT (to_jsonb(r) ? ''list_id''))::text FROM public.read_dog_share(''aaaaaaaaaaa1'') r');
SELECT security_test.check('authenticated Movies RPC strips legacy extra keys', 'true', 'SELECT (payload=''{"movies":[]}''::jsonb)::text FROM public.read_movie_share(''legacy0001'')');
ROLLBACK;
BEGIN; SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claims', '{"role":"authenticated","sub":"aaaaaaaa-1111-4111-8111-111111111111"}',true);
SELECT security_test.check('Movies owner still sees unmodified legacy bytes', 'true', 'SELECT (payload ? ''legacyExtra'')::text FROM public.shared_lists WHERE slug=''legacy0001''');
SELECT security_test.check('Movies owner can list own active and revoked', '3', 'SELECT count(*)::text FROM public.shared_lists');
SELECT security_test.check('Dogs owner can list own active and revoked', '2', 'SELECT count(*)::text FROM public.category_shared_lists');
SELECT security_test.check('Dogs owner can revoke own active', '1', 'WITH changed AS (UPDATE public.category_shared_lists SET revoked_at=now() WHERE slug=''aaaaaaaaaaa1'' RETURNING 1) SELECT count(*)::text FROM changed');
SELECT security_test.check('Dogs RPC hides just-revoked row', '0', 'SELECT count(*)::text FROM public.read_dog_share(''aaaaaaaaaaa1'')');
SELECT security_test.check('Dogs owner can restore own revoked', '1', 'WITH changed AS (UPDATE public.category_shared_lists SET revoked_at=null WHERE slug=''aaaaaaaaaaa1'' RETURNING 1) SELECT count(*)::text FROM changed');
SELECT security_test.check('Dogs restored exact link works', '1', 'SELECT count(*)::text FROM public.read_dog_share(''aaaaaaaaaaa1'')');
SELECT security_test.check('Dogs wrong category not exposed', '1', 'WITH added AS (INSERT INTO public.category_shared_lists(slug,list_id,category,payload) VALUES(''other0000001'',''user:aaaaaaaa-1111-4111-8111-111111111111'',''movies'',''{"items":[]}'') RETURNING 1) SELECT count(*)::text FROM added');
SELECT security_test.check('Dogs RPC rejects active wrong category', '0', 'SELECT count(*)::text FROM public.read_dog_share(''other0000001'')');
SELECT security_test.check('Movies owner cannot modify foreign share', '0', 'WITH changed AS (UPDATE public.shared_lists SET revoked=true WHERE slug=''bbbbbbbbb1'' RETURNING 1) SELECT count(*)::text FROM changed');
SELECT security_test.check('Dogs owner cannot modify foreign share', '0', 'WITH changed AS (UPDATE public.category_shared_lists SET revoked_at=now() WHERE slug=''bbbbbbbbbbb1'' RETURNING 1) SELECT count(*)::text FROM changed');
ROLLBACK;

BEGIN; SET LOCAL ROLE anon;
SELECT security_test.check('anonymous public columns denied shared_lists', 'error:42501', 'SELECT slug,payload FROM public.shared_lists');
SELECT security_test.check('anonymous public columns filtered by exact slug still denied shared_lists', 'error:42501', 'SELECT slug,payload FROM public.shared_lists WHERE slug=''aaaaaaaaa1''');
SELECT security_test.check('anonymous public columns denied category_shared_lists', 'error:42501', 'SELECT slug,payload FROM public.category_shared_lists');
SELECT security_test.check('anonymous public columns filtered by exact slug still denied category_shared_lists', 'error:42501', 'SELECT slug,payload FROM public.category_shared_lists WHERE slug=''aaaaaaaaa1''');
SELECT security_test.check('read_movie_share explicit definer fixed empty search path', 'true', 'SELECT (prosecdef AND proconfig = ARRAY[''search_path=""''])::text FROM pg_proc WHERE oid=''public.read_movie_share(text)''::regprocedure');
SELECT security_test.check('read_movie_share PUBLIC execution denied', '0', 'SELECT count(*)::text FROM pg_proc p, LATERAL aclexplode(p.proacl) a WHERE p.oid=''public.read_movie_share(text)''::regprocedure AND a.grantee=0 AND a.privilege_type=''EXECUTE''');
SELECT security_test.check('read_dog_share explicit definer fixed empty search path', 'true', 'SELECT (prosecdef AND proconfig = ARRAY[''search_path=""''])::text FROM pg_proc WHERE oid=''public.read_dog_share(text)''::regprocedure');
SELECT security_test.check('read_dog_share PUBLIC execution denied', '0', 'SELECT count(*)::text FROM pg_proc p, LATERAL aclexplode(p.proacl) a WHERE p.oid=''public.read_dog_share(text)''::regprocedure AND a.grantee=0 AND a.privilege_type=''EXECUTE''');
ROLLBACK;
BEGIN; SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claims', '{"sub":"aaaaaaaa-1111-4111-8111-111111111111","role":"authenticated"}', true);
SELECT security_test.check('Movies revoke RETURNING succeeds', '1', 'WITH changed AS (UPDATE public.shared_lists SET revoked=true WHERE slug=''aaaaaaaaa1'' RETURNING slug,payload,revoked) SELECT count(*)::text FROM changed');
SELECT security_test.check('Movies RPC hides just revoked', '0', 'SELECT count(*)::text FROM public.read_movie_share(''aaaaaaaaa1'')');
SELECT security_test.check('Movies un-revoke succeeds', '1', 'WITH changed AS (UPDATE public.shared_lists SET revoked=false WHERE slug=''aaaaaaaaa1'' RETURNING slug,payload,revoked) SELECT count(*)::text FROM changed');
SELECT security_test.check('Movies RPC restores same link', '1', 'SELECT count(*)::text FROM public.read_movie_share(''aaaaaaaaa1'')');
ROLLBACK;
